{% set version = "1.5.0" %}

package:
  name: pyxtf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyxtf/pyxtf-{{ version }}.tar.gz
  sha256: a7960b64d13b810b69b08fff1117cc2dbf204575ddc97027f8e3f727e7b5f977

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - numpy >=1.11
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.11

test:
  imports:
    - pyxtf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/oysstu/pyxtf
  summary: eXtended Triton Format (XTF) file interface
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oysstu
